### ISSUE TITLE
Need toggle(s) for crafting thresholds

### ISSUE THREAD

**Issue by Quizer85** [PrincessRTFM/AutoKittens#12]
There is no way to turn off the crafting thresholds, which is causing some issues. Specifically it seems that it somehow interferes with the conversion of coal and iron to steel when coal is full but iron is low. Currently I can only pick a different percentage value, but I cannot disable the additional condition.

**Comment by VariableVixen** [comment]
This is as intended, so that you don't drain all of one resource in crafting just because you happen to have a lot of another. Furthermore, to allow individual control of each threshold would require another overhaul to the autocrafting system and easily double the number of places bugs could pop up. If you want to override the thresholds entirely, use manual crafting since you'd need to be present to toggle them on and off anyway.

**Comment by Quizer85** [comment]
This is really bad. The old implementation was smart in limiting steel crafting by coal only, since that means you are never wasting either resource.

If coal is high, then it would produce steel while slowing down iron, which is fine and desirable, because iron production tends to be roughly twice of whatever coal production is anyway. If iron is high, then it would just make plates with the excess iron while coal recovers. It was the perfect way do it.

Until this gets fixed, I'm going to have to stick with the previous version of the script where Unicorn Selection was the last thing that was fixed. Personally, I don't believe adding more autocrafting recipes including non-limited crafts is worth making any of the existing automations run less smoothly.

**Comment by VariableVixen** [comment]
Okay, I think I see what you're saying now. You mean that when coal is high and iron is low, you _want_ it to craft steel anyway, since iron production so outstrips coal, rather than waiting until iron rises? That does make sense, I misunderstood earlier. I thought this was a bug report, not a desired feature.

Barring an explicit check for the exact recipe details, I'm not sure how I'd do this in a reasonable way... but I think that checking _production_ might work. Alternatively, if this is the only one in question where this happens, an explicit check might be okay.

**Comment by Quizer85** [comment]
I do think having individual controls for each crafting operation is desirable, even though it's going to be tricky to fit it in the interface without having them take up half a page each. At the very least we're going to need to be able to turn off any additional conditions.

Anyway, I think coal + iron = steel is the only crafting operation that uses more than one kind of storage-limited input. So if you refrain from messing with how the script handles those, I think it should be fine? The additional conditions should all be imposed by trying to maintain levels of non-limited resources.

**Comment by VariableVixen** [comment]
Hang on, hang on... the uncapped resources still get checked exactly the same way, the "breaking" change in question here is that now _all_ inputs are automatically considered. Before, it _only_ looked at coal when deciding whether to make steel or not. It sounds like what you want is for steel crafting to go back to that, only checking iron levels. For the UI, the problem is that I can only do so much dynamically in there, and I _will_ only do so much statically. The more I have to manually implement rather than having it look at the relevant area and automatically calculate what it needs, the more bugs are going to come up.

_After_ the UI overhaul, I should be able to at least make _some_ panels - like this one, only constructed once, based on the crafting input cache that the crafting loop itself uses. At that point, dynamically setting up toggles for what inputs to check for crafting will be... _doable_, at least.

**Comment by Quizer85** [comment]
Yeah, steel crafting has to go back to looking at coal only. If both coal and iron are checked, then it will basically never craft steel, since iron at max capacity is already being turned into plates. If we implement the tick-based throttle idea I had, the players can still deal with the (unlikely) case of coal production being higher than iron production.

**Comment by VariableVixen** [comment]
Mmm, okay. I see the problem now. Definitely a bug.

**Comment by VariableVixen** [comment]
The UI overhaul is Coming Eventually™, but for now, this has been monkey patched with a specific check. After the overhaul, I'll open new issues for new problems relating to (or fixable because of) whatever changes it introduces.
