### ISSUE TITLE
Suggestion: add a ability to throttle crafting based on ticks

### ISSUE THREAD

**Issue by Quizer85** [PrincessRTFM/AutoKittens#2]
The problem when autocrafting alloy is that it typically eats through your steel reserves extremely quickly. It would be nice if there was a way to throttle it.

I think a good way to modulate it might be to only let it attempt the crafting operation every X number of ticks (which the user is able to set).

Leaving a % amount relative to the already existing amount of alloy also seems like a workable option. You could have a field that says "Preserve an amount of steel [___] times your alloy amount". (Would probably need to guard against division by zero or something for that...)

A less useful way would be to require the script to leave X amount of steel, similar to the already existing bit that forces manuscript crafting to leave 2500 parchment for festivals. Not my preferred solution, but better than nothing, which is what we have now.

**Comment by VariableVixen** [comment]
I think that what I'll need to do is slightly overhaul the autocrafting code, to let it understand multiple inputs. From there, I can add a setting that only lets secondary crafts (ones that use uncapped resources) run if the uncapped inputs are all at least *X*% of the crafting product or something similar. It would be _possible_ as the code is, but it would messy and a terrible hack.

**Comment by Quizer85** [comment]
Might not be a bad idea to add a toggle for each resource to allow both methods to be used. Each has its pros and cons in different situations.

If we do this thing where it's based on the percentage of the other, uncapped input resource, we're going to have to automate other uncapped resources as well, such as slabs and scaffolds. Honestly, that might be a good idea anyway for trade, so the script can maintain a supply of the resource needed for trade, and / or throttle the frequency of trading attempts so as not to consume it all.

**Comment by VariableVixen** [comment]
Hmm... this does complicate things a little. I was thinking for all resource inputs, if it's capped then do what it's been doing, but if not then require that it be at least some user-defined percentage of the _current_ level of the output resource. If you set that to 10%, then it'll only craft, say, beams if you have at least 10% as much wood as you currently have beams. But it would be a compound condition, requiring that _all_ input resources meet their minimum thresholds, whatever they may be. The bottom line would be that existing crafts would be _mostly_ unaffected, the ones that are changed should be changed for the better so you don't burn through all of one thing just because you have a lot of the other, and it would enable the possibility of autocrafting everything that _can_ be crafted. Thoughts?

**Comment by Quizer85** [comment]
This is what I was thinking:

![image](https://user-images.githubusercontent.com/14056473/62195934-56335780-b37d-11e9-90db-e71e7698cf45.png)

**Comment by VariableVixen** [comment]
Possible, but slightly less than optimal. It'd need a tick counter, which I'd worry about overflowing. Getting the LCM of all tick intervals and resetting it at that tick would probably work, at least...

The problem is that you're asking for too many things in the autocrafting loop. I can implement most of them, _individually_. But as an earlier test showed me, _anything_ that happens every game tick needs to be minimally expensive, computationally. An experiment with the timer formatting was a little _too_ expensive and it resulted in a fully unresponsive tab after a certain time. Not even a render. I'm all for highly-granular control, but I need to keep the processing minimal or else the script not only stops working, it starts killing the game too, and that's not even considering the natural increase in bugs from the complexity. It's an airplane problem: a twin engine plane has twice as many engine problems as a single-engine plane does.

**Comment by Quizer85** [comment]
Yeah, I can see what you're getting at. I'll try to keep my creative impulses in check a little.

Are you sure it's better to have a single tick counter that every recipe would interact with? I was thinking each recipe would have its own tick counter that increments to the value in the input field and is only given the go-ahead to craft when it reaches it, after which it is zeroed out. That way, you wouldn't have to mess around calculating the LCMs of various tick intervals which change every time the user changes the settings (I imagine that might end up being the most expensive part of this), and since the recipes are dealt with one by one anyway every tick, I wouldn't really expect it to be significantly computationally expensive to have one tick counter per recipe that gets incremented as that recipe is being handled. Anyway, since this would stop a bunch of crafting attempts before the script even needs to check resource levels, shouldn't that save a bunch of cycles in practice?

At least that's my naive model of how this might work; I'm in no way an expert on this.

**Comment by VariableVixen** [comment]
That, honestly, would probably work better. They wouldn't even be saved in the settings - unless you set it to a stupidly large value, it won't matter - so having a handful of variables for that would actually work better.

For reference, that matters because linting the file can easily find typos in variable names or places where something looks wrong with one, but _object properties_ like the settings are much harder.

This would be pretty reasonably to implement, but I need to do the UI first... a lot things seem to hinge on that.
