### ISSUE TITLE
Suggestion: find a way to run Lunar Outpost only part of the time

### ISSUE THREAD

**Issue by Quizer85** [PrincessRTFM/AutoKittens#3]
When first unlocking Unobtainium via Lunar Outpost, you can't really afford to run the building full-time because your Uranium income isn't going to be that high. It would be nice to automate toggling the building on and off in a way that does not totally deplete Uranium.

My first idea was being able to set a maximum Uranium threshold where it would activate, and a minimum Uranium threshold where it would stop, using the already existing percentage value dropdown that is used elsewhere.
But that might lead to trouble if the user inputs stupid values, and coding restrictions on what the user is allowed to select would probably be a pain. Might have to brainstorm some other way to do it.

Also, turning production buildings on and off isn't something that's been done in this script before, which might make it more difficult.

Anyway, this might cease to be a problem in later runs when you're more powerful. If it's too difficult / time-consuming to do, you can skip it.

**Comment by VariableVixen** [comment]
It's not that hard to turn buildings on and off, but it would be a little messy to determine _how many_ to toggle. Furthermore, the outpost only pulls `0.35` uranium per second, which isn't _that_ hard to pass in terms of production (although I _have_ been running the game almost non-stop up to year 2000 already...) so this is probably a lower priority.

I'm willing to look into it, but let me ask this: if the player has more than one outpost, should the script shut down only as many as needed to make uranium a net gain, or should it shut down _all_ of them? And if multiple outposts are offline when passing the enabling threshold, how many should come back online? All of them? We can't be sure the player won't have closed the page since the script turned them off, so there's no guarantee that we'll be able to remember how many were disabled.

**Comment by Quizer85** [comment]
Probably best to just disable enough to allow positive uranium production, then enable enough to start consuming the stockpile when storage gets full / to the specified amount. You can set it up so it disables / enables one every few ticks (to give it time for the numbers to update and keep doing that until it hits the threshold that was set.

The use case I'm most worried about is early on when you only have a single outpost. You want to produce unobtainium, but you might want to keep some uranium around, too. Like I said, there's a good chance this won't even be a problem in later runs with more paragon and karma and whatnot. I'll let you decide whether this is worth spending time on. Unlike when I used to play several years back, buildings are now capable of running on an empty resource and just throttle their conversion accordingly. They used to just turn themselves off the instant they ran out of resources.

**Comment by VariableVixen** [comment]
Like I said, I haven't even got the oil capacity to buy a single outpost yet but I'm making more uranium than one outpost would need. I'll leave it on the list, but it'll be a dogwash.

**Comment by WrayOfSunshine** [comment]
This appears to be implemented - just making sure I'm not misunderstanding the Lunar Outposts section of the crafting options... right?

**Comment by VariableVixen** [comment]
I'm gonna be honest, I haven't played AK in over a year, so I don't really remember much with this script. But I checked the code and it looks like it does the job, so I guess past me forgot to close the issue when she implemented this.
